### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by franky47** [SocialGouv/e2esdk#10]
## Client
- [ ] Real-time notifications via WebSocket + SharedWorker, gracefully degraded to polling where SW aren't available.
- [ ] Configure persistance ("remember me for N days")

## Server
- [ ] Add audit logs

## Devtools
- [ ] Investigate passing a live Client as "props" rather than creating a dedicated one
- [ ] Allow configuring position & size, for static panel vs drawer behaviour

## Examples
- [ ] Add contact form example from https://github.com/SocialGouv/chiffrement-sandbox

## Other
- [ ] Add CI
- [ ] Investigate [Changesets](https://github.com/changesets/changesets) for versioning packages
- [ ] Investigate [Verdaccio](https://github.com/verdaccio/verdaccio) for local NPM deployment testing
- [ ] Deploy to SocialGouv's internal NPM registry for testing
- [ ] Deploy Docker image to SocialGouv's container registry
- [ ] Add CD
